#ifndef SYSCALL_CODES_H
#define SYSCALL_CODES_H

#define SYSCALL_MEM_ALLOC 0x00
#define SYSCALL_MEM_FREE 0x01

#define SYSCALL_THREAD_CREATE 0x11
#define SYSCALL_THREAD_EXIT 0x12
#define SYSCALL_THREAD_DISPATCH 0x13

#define SYSCALL_SEM_OPEN 0x21
#define SYSCALL_SEM_CLOSE 0x22
#define SYSCALL_SEM_WAIT 0x23
#define SYSCALL_SEM_SIGNAL 0x24
#define SYSCALL_SEM_WAIT_N 0x25
#define SYSCALL_SEM_SIGNAL_N 0x26

#define SYSCALL_TIME_SLEEP 0x31

#define SYSCALL_GETC 0x41
#define SYSCALL_PUTC 0x42

#endif // SYSCALL_CODES_H